
# Technical Skills with One WOrd Token
technical_tokens = [
    'agile',
    'scrum',
    'kanban',
    'jira',
    'excel',
    'sql',
    'python',
    'r',
    'c',
    'c lang',
    'c++',
    'c#',
    'java',
    'javascript',
    'sap',
    'salesforce',
    'tableau',
    'looker',
    'qgis',
    'arcgis',
    'dashboard',
    'dashboards',
    'statistics',
    'probability',
    'powerpoint',
    'vlookup',
    'pyspark',
    'regression',
    'classification',
    'clustering',
    'linux',
    'bash',
    'git',
    'gitlab',
    'dvc',
    'logging',
    'aws',
    'azure',
    'gcp',
    'mysql',
    'nosql',
    'postgresql',
    'oracle',
    'mongodb',
    'cassandra',
    'etl',
    'elt',
    'snowflake',
    'databricks',
    'hadoop',
    'bigquery',
    'pandas',
    'numpy',
    'scipy',
    'statsmodels',
    'matplotlib',
    'seaborn',
    'plotly',
    'bokeh',
    'altair',
    'scikit learn',
    'xgboost',
    'tensorflow',
    'keras',
    'pytorch',
    'beautifulsoup4',
    'scrapy',
    'spark',
    'pyspark',
    'sqlalchemy',
    'pymongo',
    'statsmodels',
    'pymc3',
    'openpyxl',
    'dplyr',
    'ggplot2',
    'tidyr',
    'readr',
    'stringr',
    'lubridate',
    'caret',
    'randomforest',
    'xgboost',
    'shiny',
    'plotly',
    'tibble',
    'purrr',
    'forcats',
    'janitor',
    'knitr',
    'rmarkdown',
    'roxygen2',
    'data visualization',
    'power bi',
    'data intelligence',
    'data cleaning',
    'data transformation',
    'data validation',
    'statistical analysis',
    'time series analysis',
    'geo spatial analysis',
    'google earth engine',
    'pivot tables',
    'data warehouse',
    'bi tools',
    'google data studio',
    'scripting language',
    'shell scripting',
    'bash scripting',
    'web scraping',
    'relational databases',
    'nosql databases',
    'data modeling',
    'data strategy',
    'data architecture',
    'etl processes',
    'performance metrics',
    'predictive analytics',
    'descriptive analytics',
    'diagnostic analytics',
    'prescriptive analytics',
    'ad hoc',
    'data lifecycle',
    'machine learning',
    'data mining',
    'big data',
    'predictive modeling',
    'statistical modeling',
    'statistical methods',
    'regression analysis',
    'dimensionality reduction',
    'supervised learning',
    'unsupervised learning',
    'linear regression',
    'logistic regression',
    'feature engineering',
    'feature selection',
    'data preprocessing',
    'version control',
    'data version control',
    'google cloud platform',
    'google analytics',
    'customer segmentation',
    'ab testing',
    'hypothesis testing',
    'data pipelines',
    'data integration',
    'data lake',
    'data warehouse',
    'aws glue',
    'data dictionary',
    'etl development',
    'data extraction',
    'data transformation',
    'data loading',
    'sql server',
    'data mapping',
    'data marts',
    'job scheduling',
    'workflow automation',
    'data pipeline monitoring',
    'data cleansing',
]



# Soft skill tokens
soft_skills_tokens = [
    'adaptability',
    'creativity',
    'leadership',
    'empathy',
    'flexibility',
    'resilience',
    'networking',
    'negotiation',
    'coaching',
    'mentoring',
    'innovation',
    'dependability',
    'collaboration',
    'documentation',
    'benchmarking',
    'forecasting',
    'sustainability',
    'presentation',
    'data presentation',
    'communication skills',
    'team collaboration',
    'problem solving',
    'critical thinking',
    'time management',
    'attention to detail',
    'interpersonal skills',
    'decision making',
    'conflict resolution',
    'emotional intelligence',
    'work ethic',
    'self motivation',
    'customer service',
    'active listening',
    'public speaking',
    'strategic thinking',
    'project management',
    'organizational skills',
    'analytical thinking',
    'analytical skills',
    'data interpretation',
    'data reporting',
    'business analytics',
    'business intelligence',
    'market research',
    'data management',
    'data governance',
    'data security',
    'data privacy',
    'agile methodology',
    'stakeholder management',
    'client interaction',
    'user experience',
    'user interface',
    'technical writing',
    'business process improvement',
    'risk management',
    'cost management',
    'resource management',
    'change management',
    'performance optimization',
    'quality assurance',
    'operational efficiency',
    'strategic planning',
    'innovation management',
    'trend analysis',
    'scenario planning',
    'corporate social responsibility',
    'cultural awareness'
]



# Education requirement tokens
education_tokens = [
    'bachelors',
    'bachelor',
    "bachelor's", 
    'masters',
    'master',
    "master's",
    'phd',
    'doctorate',
    'certification',
    'diploma',
    'postgraduate',
    'bs degree',
    'ba degree',
    'b s degree',
    'b a degree',
    'information technology',
    'computer science',
    'mathematics',
    'economics',
    'accredited university',
    'professional certificate',
    'technical degree',
    'advanced degree'
]