
# Technical Skills with One WOrd Token
technical_skills = [
    'agile',
    'scrum',
    'kanban',
    'jira',
    'confluence',
    'excel',
    'sql',
    'python',
    'r',
    'c',
    'c++',
    'c#',
    'java',
    'javascript',
    'cuda',
    'tableau',
    'looker',
    'qgis',
    'arcgis',
    'kpi',
    'dashboard',
    'powerpoint',
    'vlookup',
    'analytics',
    'hadoop',
    'spark',
    'nlp',
    'classification',
    'clustering',
    'mlops',
    'linux',
    'bash',
    'devops',
    'mlops',
    'ci/cd',
    'containerization',
    'docker',
    'kubernetes',
    'kubeflow',
    'mlflow',
    'tfx',
    'git',
    'dvc',
    'monitoring',
    'logging',
    'aws',
    'azure',
    'gcp',
    'cro',
    'mysql',
    'postgresql',
    'oracle',
    'mongodb',
    'cassandra',
    'etl',
    'elt',
    'snowflake',
    'redshift',
    'bigquery',
    'airflow',
    'jupyter',
    'notebook',
    'anaconda',
    'pandas',
    'numpy',
    'scipy',
    'matplotlib',
    'seaborn',
    'plotly',
    'bokeh',
    'altair',
    'xgboost',
    'lightgbm',
    'tensorflow',
    'keras',
    'pytorch',
    'tfx',
    'nltk',
    'spacy',
    'gensim',
    'beautifulsoup4',
    'requests',
    'scrapy',
    'pyspark',
    'dask',
    'vaex',
    'sqlalchemy',
    'pyodbc',
    'pymongo',
    'statsmodels',
    'pymc3',
    'tqdm',
    'joblib',
    'openpyxl',
    'xlrd',
    'xlwt',
    'json',
    'csv',
    'yaml',
    'configparser',
    'os',
    'sys',
    'logging',
    're',
    'dplyr',
    'ggplot2',
    'tidyr',
    'readr',
    'stringr',
    'lubridate',
    'caret',
    'randomforest',
    'xgboost',
    'shiny',
    'plotly',
    'tibble',
    'purrr',
    'forcats',
    'janitor',
    'mlmetrics',
    'e1071',
    'glmnet',
    'rpart',
    'nnet',
    'gbm',
    'htmlwidgets',
    'dt',
    'knitr',
    'rmarkdown',
    'roxygen2',
    'devtools',
    'chatgpt',
    'copilot',
    'gemini',
    'claude'
]



# Technical skills with Multi Words Expression
technical_mwe = [
    'business analysis',
    'business requirements',
    'functional requirements',
    'non-functional requirements',
    'swot analysis',
    'cost-benefit analysis',
    'risk analysis',
    'data analysis',
    'data visualization',
    'power bi',
    'data cleaning',
    'data transformation',
    'data validation',
    'statistical analysis',
    'time-series analysis',
    'geo-spatial analysis',
    'google earth engine', 
    'data reporting',
    'pivot tables',
    'data warehousing',
    'microsoft excel',
    'ms excel',
    'microsoft powerpoint',
    'ms powerpoint',
    'business intelligence',
    'bi tools',
    'data-driven decision making',
    'data modeling',
    'data governance',
    'data strategy',
    'data architecture',
    'etl processes',
    'performance metrics',
    'predictive analytics',
    'descriptive analytics',
    'diagnostic analytics',
    'prescriptive analytics',
    'data lifecycle',
    'machine learning',
    'deep learning',
    'artificial intelligence',
    'neural networks',
    'parallel computing',
    'data mining',
    'big data',
    'natural language processing',
    'computer vision',
    'predictive modeling',
    'statistical modeling',
    'regression analysis',
    'dimensionality reduction',
    'model training',
    'model evaluation',
    'hyperparameter tuning',
    'cross-validation',
    'supervised learning',
    'unsupervised learning',
    'reinforcement learning',
    'feature engineering',
    'feature selection',
    'data preprocessing',
    'algorithm development',
    'model deployment',
    'ml pipelines',
    'continuous integration',
    'continuous deployment',
    'model monitoring',
    'model optimization',
    'tensorflow extended',
    'version control',
    'data version control',
    'model tracking',
    'model serving',
    'model registry',
    'model evaluation',
    'pipeline orchestration',
    'automated testing',
    'cloud platforms',
    'google cloud platform',
    'databricksweb analytics',
    'google analytics',
    'customer segmentation',
    'a/b testing',
    'conversion rate optimization',
    'data pipeline',
    'data integration',
    'data lake',
    'data warehouse',
    'batch processing',
    'stream processing',
    'apache kafka',
    'apache flink',
    'aws glue',
    'data orchestration',
    'data governance',
    'data quality',
    'data catalog',
    'etl development',
    'data extraction',
    'data transformation',
    'data loading',
    'sql server',
    'data mapping',
    'data staging',
    'data mart',
    'data lineage',
    'job scheduling',
    'workflow automation',
    'data pipeline monitoring',
    'data cleansing',
    'scikit-learn'
]



# Soft Skills with One Word Token
soft_skills = [
    'adaptability',
    'creativity',
    'leadership',
    'empathy',
    'flexibility',
    'resilience',
    'networking',
    'negotiation',
    'coaching',
    'mentoring',
    'innovation',
    'dependability',
    'collaboration',
    'programming',
    'coding',
    'devops',
    'scrum',
    'kanban',
    'documentation',
    'benchmarking',
    'forecasting',
    'sustainability'
]



# Soft Skills with Multi Words Expression
soft_skills_mwe = [
    'communication skills',
    'team collaboration',
    'problem-solving',
    'critical thinking',
    'time management',
    'attention to detail',
    'interpersonal skills',
    'decision-making',
    'conflict resolution',
    'emotional intelligence',
    'work ethic',
    'self-motivation',
    'customer service',
    'active listening',
    'public speaking',
    'strategic thinking',
    'project management',
    'organizational skills',
    'analytical thinking',
    'analytical skills',
    'technical skills',
    'data interpretation',
    'data analysis',
    'data reporting',
    'quantitative analysis',
    'qualitative analysis',
    'business analytics',
    'market research',
    'data management',
    'data governance',
    'data integration',
    'data security',
    'data privacy',
    'statistical modeling',
    'software development',
    'system design',
    'it infrastructure',
    'cloud infrastructure',
    'continuous integration',
    'continuous deployment',
    'agile methodology',
    'stakeholder management',
    'client interaction',
    'user experience',
    'user interface',
    'technical writing',
    'business process improvement',
    'financial analysis',
    'risk management',
    'cost management',
    'resource management',
    'change management',
    'performance optimization',
    'quality assurance',
    'operational efficiency',
    'strategic planning',
    'innovation management',
    'trend analysis',
    'scenario planning',
    'corporate social responsibility',
    'cultural awareness'
]



# Education requirement tokens with One Word
education_requirement = [
    'bachelors',
    'bachelor',
    'masters',
    'master',
    'phd',
    'doctorate',
    'IT',
    'CS',
    'statistics',
    'mathematics',
    'maths',
    'engineering',
    'business',
    'finance',
    'economics',
    'physics',
    'certification',
    'diploma',
    'postgraduate'
]



# Education Requirement with MWE
education_mwe = [
    "bachelor's degree",
    "master's degree",
    'information technology',
    'computer science',
    'data science',
    'higher education',
    'formal education',
    'accredited university',
    'professional certificate',
    'technical degree',
    'advanced degree'
]