
# Technical Skills with One WOrd Token
technical_tokens = [
    'agile',
    'scrum',
    'kanban',
    'jira',
    'confluence',
    'excel',
    'sql',
    'python',
    'r',
    'c',
    'c lang',
    'c++',
    'c#',
    'c sharp',
    'java',
    'javascript',
    'cuda',
    'sap',
    'tableau',
    'looker',
    'qgis',
    'arcgis',
    'kpi',
    'dashboard',
    'dashboards',
    'kpis',
    'statistics',
    'probability',
    'powerpoint',
    'vlookup',
    'hadoop',
    'hive',
    'spark',
    'pyspark',
    'nlp',
    'regression'
    'classification',
    'clustering',
    'mlops',
    'linux',
    'bash',
    'devops',
    'mlops',
    'containerization',
    'docker',
    'kubernetes',
    'kubeflow',
    'mlflow',
    'tfx',
    'git',
    'gitlab',
    'cml',
    'dvc',
    'logging',
    'aws',
    'azure',
    'gcp',
    'cro',
    'mysql',
    'nosql',
    'postgresql',
    'oracle',
    'mongodb',
    'cassandra',
    'etl',
    'elt',
    'snowflake',
    'databricks',
    'redshift',
    'bigquery',
    'airflow',
    'jupyter',
    'notebook',
    'anaconda',
    'pandas',
    'numpy',
    'scipy',
    'statsmodels',
    'matplotlib',
    'seaborn',
    'plotly',
    'bokeh',
    'altair',
    'scikit learn',
    'xgboost',
    'lightgbm',
    'tensorflow',
    'keras',
    'pytorch',
    'tfx',
    'nltk',
    'spacy',
    'kafka',
    'gensim',
    'beautifulsoup4',
    'scrapy',
    'pyspark',
    'dask',
    'vaex',
    'sqlalchemy',
    'pyodbc',
    'pymongo',
    'statsmodels',
    'pymc3',
    'tqdm',
    'joblib',
    'openpyxl',
    'xlrd',
    'xlwt',
    'json',
    'csv',
    'yaml',
    'configparser',
    'os',
    'sys',
    'logging',
    'regular expression',
    'streamlit',
    'dplyr',
    'ggplot2',
    'tidyr',
    'readr',
    'stringr',
    'lubridate',
    'caret',
    'randomforest',
    'xgboost',
    'shiny',
    'plotly',
    'tibble',
    'purrr',
    'forcats',
    'janitor',
    'mlmetrics',
    'e1071',
    'glmnet',
    'rpart',
    'nnet',
    'gbm',
    'htmlwidgets',
    'dt',
    'knitr',
    'rmarkdown',
    'roxygen2',
    'devtools',
    'chatgpt',
    'copilot',
    'gemini',
    'claude',
    'data visualization',
    'power bi',
    'data intelligence',
    'data cleaning',
    'data transformation',
    'data validation',
    'statistical analysis',
    'time series analysis',
    'geo spatial analysis',
    'google earth engine',
    'pivot tables',
    'data warehouse',
    'bi tools',
    'google data studio',
    'scripting language',
    'shell scripting',
    'bash scripting',
    'web scraping',
    'relational databases',
    'nosql databases',
    'data modeling',
    'complex modeling',
    'data strategy',
    'data architecture',
    'etl processes',
    'performance metrics',
    'predictive analytics',
    'descriptive analytics',
    'diagnostic analytics',
    'prescriptive analytics',
    'ad hoc analyses',
    'ad hoc reports',
    'data lifecycle',
    'machine learning',
    'deep learning',
    'artificial intelligence',
    'neural networks',
    'parallel computing',
    'data mining',
    'big data',
    'complex datasets',
    'natural language processing',
    'computer vision',
    'predictive modeling',
    'statistical modeling',
    'statistical methods',
    'regression analysis',
    'dimensionality reduction',
    'model testing',
    'model training',
    'model evaluation',
    'hyperparameter tuning',
    'cross validation',
    'supervised learning',
    'unsupervised learning',
    'reinforcement learning',
    'linear regression',
    'logistic regression',
    'decision tree regression',
    'random forest',
    'k nearest neighbors',
    'kmeans clustering',
    'pca',
    'feature engineering',
    'feature selection',
    'data preprocessing',
    'algorithm development',
    'model deployment',
    'ml pipelines',
    'ci cd',
    'continuous integration',
    'continuous deployment',
    'model monitoring',
    'model optimization',
    'tensorflow extended',
    'version control',
    'data version control',
    'model tracking',
    'model serving',
    'model registry',
    'model evaluation',
    'pipeline orchestration',
    'automated testing',
    'cloud platforms',
    'google cloud platform',
    'databricksweb analytics',
    'google analytics',
    'customer segmentation',
    'ab testing',
    'hypothesis testing',
    'conversion rate optimization',
    'data pipeline',
    'data pipelines',
    'data integration',
    'data lake',
    'data warehouse',
    'batch processing',
    'stream processing',
    'distributed computing',
    'apache kafka',
    'apache flink',
    'aws glue',
    'data orchestration',
    'data dictionary',
    'etl development',
    'data extraction',
    'data transformation',
    'data loading',
    'sql server',
    'data mapping',
    'data mart',
    'data marts',
    'job scheduling',
    'workflow automation',
    'data pipeline monitoring',
    'data cleansing',
]



# Soft skill tokens
soft_skills_tokens = [
    'adaptability',
    'creativity',
    'leadership',
    'empathy',
    'flexibility',
    'resilience',
    'networking',
    'negotiation',
    'coaching',
    'mentoring',
    'innovation',
    'dependability',
    'collaboration',
    'scrum',
    'kanban',
    'documentation',
    'benchmarking',
    'forecasting',
    'sustainability',
    'presentation',
    'data presentation',
    'communication skills',
    'team collaboration',
    'problem solving',
    'critical thinking',
    'time management',
    'attention to detail',
    'interpersonal skills',
    'decision making',
    'conflict resolution',
    'emotional intelligence',
    'work ethic',
    'self motivation',
    'customer service',
    'active listening',
    'public speaking',
    'strategic thinking',
    'project management',
    'organizational skills',
    'analytical thinking',
    'analytical skills',
    'data interpretation',
    'data reporting',
    'business analytics',
    'business intelligence',
    'market research',
    'data management',
    'data governance',
    'data security',
    'data privacy',
    'agile methodology',
    'stakeholder management',
    'client interaction',
    'user experience',
    'user interface',
    'technical writing',
    'business process improvement',
    'risk management',
    'cost management',
    'resource management',
    'change management',
    'performance optimization',
    'quality assurance',
    'operational efficiency',
    'strategic planning',
    'innovation management',
    'trend analysis',
    'scenario planning',
    'corporate social responsibility',
    'cultural awareness'
]



# Education requirement tokens
education_tokens = [
    'bachelors',
    'bachelor',
    'masters',
    'master',
    'phd',
    'doctorate',
    'certification',
    'diploma',
    'postgraduate',
    "bachelor's degree",
    'bachelor degree',
    'bachelors degree',
    "master's degree",
    'master degree',
    'masters degree',
    'bs degree',
    'ba degree',
    'b s degree',
    'b a degree',
    'information technology',
    'computer science',
    'accredited university',
    'professional certificate',
    'technical degree',
    'advanced degree'
]